### PR TITLE
Removed the errorneos purple colour in menu

### PR DESCRIPTION
**Pull request by cganesh8**
@Subra730 ,

I the startup menu screen colour to white. Actually it wasn't that straight forward. It was an error actually due to our placing of the tachyons parameters.

Finally fixed it and also cleaned up the list line which was not needed... i think.

Please review.

### CODE REVIEW

**Comment by cganesh8** [comment]
@Subra730 , also cleaned up the menu by removing signup and keeping register

**Review by Subra730 — APPROVED** [review]
Code looks neater, easier to understand now

**Comment by Subra730** [comment]
@cganesh8 changes made

**Comment by Subra730** [comment]
@cganesh8 this time got it right

**Pull request merged**
